/*[]-----------------------------------------------------------------[]*/
/*|                     CERTIFICAÇÃO OCA                              |*/
/*|*******************************************************************|*/
/*|  Book.......: OCA Oracle database       Data..: 02.10.2018	      |*/
/*|  Cap_02.....: Oracle	and	Structured	Query	Language (SQL)    |*/
/*|  @Author....: Jefferson                                           |*/
/*|  Info.......: No capítulo 1 mostrou uma abordagem                 |*/
/*|               geral do que será estudado no livro.                |*/
/*[]-----------------------------------------------------------------[]*/

-- CRIANDO A TABELA work_schedule 
CREATE TABLE HORARIO_TRABALHO(
  HORARIO_TRABALHO_ID NUMBER,
  COMECO_DATA DATE,
  FIM_DATA DATE
);

-- CRIANDO COM SITAÇÃO DE NOME
CREATE TABLE "FUNCIONARIOS DA EMPRESA" (
  FUNCIONARIO_ID NUMBER,
  NOME VARCHAR2(35)
);
SELECT * FROM "FUNCIONARIOS DA EMPRESA";

--CRIANDO TABELA CRUZEIRO COM RESTRIÇÃO
CREATE TABLE CRUZEIRO(
  CRUZEIRO_ID NUMBER,
  CRUZEIRO_TIPO_ID NUMBER,
  CRUZEIRO_NOME VARCHAR2(35),
  CAPITAO_ID NUMBER NOT NULL,
  COMECO_DATA DATE,
  FIM_DATA DATE,
  STATUS VARCHAR2(30) DEFAULT 'DOCA',
  CONSTRAINT PK_CRUZEIRO PRIMARY KEY (CRUZEIRO_ID)
);

SELECT * FROM CRUZEIRO;

-- DESCRICAO
DESCRIBE CRUZEIRO;

-- VISUALIZAR CONFIGURAÇÕES DE TERRITORIOS
SHOW PARAMETERS;
SHOW PARAMETERS NLS_DATE_FORMAT;

-- eXEMPLO DE LOBS
--	However,	LOBs	cannot be	primary	keys,	and	they	cannot	be	used	with	
-- DISTINCT,	GROUP	BY , ORDER	BY ,	or	joins. 
CREATE TABLE NOTA_CRUZEIRO(
  CRUZEIRO_ID_NOTAS NUMBER,
   CRUZEIRO_NOTAS CLOB
);

-- ALGUMAS MANEIRAS DE CRIAR RESTRIÇÕES.

CREATE TABLE PORTAS(
  PORTAS_ID NUMBER PRIMARY KEY NOT NULL,
  PORTAS_NOME VARCHAR2(10)
);
DROP TABLE TESTE_PORTA;

CREATE TABLE TESTE_PORTA(
  ID NUMBER CONSTRAINT PK_TESTE PRIMARY KEY ,
  PORTA_NOME VARCHAR2(1)
);

CREATE TABLE TESTE_PORTA(
  ID NUMBER ,
  PORTA_NOME VARCHAR2(1),
  PRIMARY KEY (ID)
);


--OUTRA MANEIRA COM ALTER

CREATE TABLE TESTE_PORTA(
  ID NUMBER ,
  PORTA_NOME VARCHAR2(1)
);

ALTER TABLE TESTE_PORTA
MODIFY ID PRIMARY KEY;

--COMANDO PARA VERIFICAR A CHAVE GERADA AUTOMATICAMENTE
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TESTE_PORTA';

ALTER TABLE TESTE_PORTA
RENAME CONSTRAINT SYS_C007425 TO PK_TESTE2;

ALTER TABLE TESTE_PORTA
ADD PRIMARY KEY (ID);

ALTER TABLE TESTE_PORTA
ADD CONSTRAINT PORT_ID_PK PRIMARY KEY(ID);

DESC TESTE_PORTA;

ALTER TABLE TESTE_PORTA
MODIFY PORTA_NOME NOT NULL;

-- TRABANDO COM CHAVES ESTRANGEIRAS
DROP TABLE PORTA;

CREATE TABLE PORTA(
  PORTA_ID NUMBER,
  PORTA_NOME VARCHAR2(10),
  PORTA_PAIS VARCHAR(20),
  CAPACIDADE NUMBER,
  PRIMARY KEY (PORTA_ID)
);


CREATE TABLE CRUZEIRO(
  CRUZEIRO_ID NUMBER,
  CRUZEIRO_NOME VARCHAR2(35),
  FK_PORTA_ID NUMBER,
  CONSTRAINT FK_NAVIO_PORTA FOREIGN KEY(FK_PORTA_ID)
                            REFERENCES PORTA(PORTA_ID)
                            
);
-- USANDO ON DELETE
DROP TABLE CRUZEIRO;
CREATE TABLE CRUZEIRO(
  CRUZEIRO_ID NUMBER,
  CRUZEIRO_NOME VARCHAR2(35),
  FK_PORTA_ID NUMBER,
  CONSTRAINT FK_NAVIO_PORTA FOREIGN KEY(FK_PORTA_ID)
                            REFERENCES PORTA(PORTA_ID)
                            ON DELETE SET NULL
                            
);

-- USANDO CASCADE
CREATE TABLE CRUZEIRO(
  CRUZEIRO_ID NUMBER,
  CRUZEIRO_NOME VARCHAR2(35),
  FK_PORTA_ID NUMBER,
  CONSTRAINT FK_NAVIO_PORTA FOREIGN KEY(FK_PORTA_ID)
                            REFERENCES PORTA(PORTA_ID)
                            ON DELETE CASCADE
                            
);

INSERT INTO PORTA VALUES(2,'TESTE2','BR',20);

INSERT INTO CRUZEIRO VALUES(10,'TESTE1',1);
INSERT INTO CRUZEIRO VALUES(20,'TESTE2',2);


SELECT * FROM PORTA;
SELECT * FROM CRUZEIRO;

DELETE FROM PORTA WHERE PORTA_ID = 2;

--USANDO O CHECK
CREATE TABLE VENDEDOR(
  VENDEDOR_ID NUMBER,
  VENDEDOR_NOME VARCHAR2(20),
  STATUS NUMBER(1) CHECK(STATUS IN (4,5)),
  CONSTRAINT PK_VENDEDOR PRIMARY KEY (VENDEDOR_ID)
);

INSERT INTO VENDEDOR(VENDEDOR_ID)VALUES(1);
SELECT * FROM VENDEDOR;
DESCRIBE VENDEDOR;
DROP TABLE VENDEDOR;

--VÁRIAS RESTRIÇÕES.
CREATE TABLE VENDEDOR(
  VENDEDOR_ID NUMBER CONSTRAINT PK_VENDEDOR PRIMARY KEY,
  VENDEDOR_NOME VARCHAR2(20) NOT NULL,
  VENDEDOR_STATUS NUMBER(1) CONSTRAINT NN_VENDEDOR NOT NULL,
  VENDEDOR_CATEGORIA VARCHAR2(20),
  CONSTRAINT CK_VENDEDOR_STATUS CHECK(VENDEDOR_STATUS IN(4,5))
);

DESCRIBE VENDEDOR;













