/*[]-----------------------------------------------------------------[]*/
/*|                     CERTIFICAÇÃO OCA                              |*/
/*|*******************************************************************|*/
/*|  BOOK.......: OCA ORACLE DATABASE       DATA..: 22.10.2018	      |*/
/*|  CAP_02.....: ORACLE	AND	STRUCTURED	QUERY	LANGUAGE (SQL)    |*/
/*|  @AUTHOR....: JEFFERSON                                           |*/
/*|  INFO.......: LABORATÓRIO 01 – COMANDOS DDL                       |*/
/*[]-----------------------------------------------------------------[]*/

--1 
CREATE SEQUENCE SQ_ID
START WITH 1
INCREMENT BY 1;

--A
CREATE TABLE TB_DVD(
    CD_DVD NUMBER CONSTRAINT PK_CD_DVD PRIMARY KEY,
    TITULO VARCHAR2(20),
    CATEGORIA VARCHAR2(20)
);

CREATE TABLE TB_CLIENTE(
    CD_CLIENTE NUMBER,
    NOME_CLIENTE VARCHAR2(20)
);
--B
ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_CD_CLIENTE PRIMARY KEY(CD_CLIENTE);


CREATE TABLE TB_LOCACAO(
    CD_CLIENTE NUMBER,
    CD_DVD NUMBER,
    VALOR NUMBER(10,2),
    DT_LOCACAO DATE,
    DT_DEVOLUCAO DATE
);

--C
ALTER TABLE TB_LOCACAO ADD CONSTRAINT PK_LOCACAO PRIMARY KEY
(CD_CLIENTE,CD_DVD,DT_LOCACAO);

--D
ALTER TABLE TB_LOCACAO ADD CONSTRAINT FK_TB_DVD FOREIGN KEY
(CD_DVD)REFERENCES TB_DVD(CD_DVD);

--E
ALTER TABLE TB_LOCACAO
    ADD CONSTRAINT FK_TB_CLIENTE FOREIGN KEY ( CD_CLIENTE )
        REFERENCES TB_CLIENTE ( CD_CLIENTE );


ALTER TABLE TB_DVD DROP CONSTRAINT FK_TB_DVD;

--2
ALTER TABLE TB_DVD ADD ANO_LANCAMENTO DATE;

--3
ALTER TABLE TB_CLIENTE ADD(
    ENDERECO VARCHAR2(20),
    CPF VARCHAR2(20)
);

--4
CREATE TABLE TB_CLIENTE(
    CD_CLIENTE NUMBER(4) PRIMARY KEY,
    NM_CLIENTE VARCHAR2(50) NOT NULL,
    ENDERECO VARCHAR2(60) CONSTRAINT NN_ENDERECO NOT NULL,
    TELEFONE1 VARCHAR2(10),
    TELEFONE2 VARCHAR2(10),
    RG VARCHAR2(20) CONSTRAINT NN_RG NOT NULL,
    DT_REGISTRO DATE DEFAULT SYSDATE
);

--5
--A
INSERT INTO TB_CLIENTE VALUES(1, 'JEFF','CENTRO','99','99','111','10/02/2007');
INSERT INTO TB_CLIENTE VALUES(2, 'MORGAN','CENTRO','99','99','111','10/02/2007');

--B
INSERT INTO TB_CLIENTE(CD_CLIENTE,NM_CLIENTE,ENDERECO,TELEFONE1,RG,DT_REGISTRO) VALUES(3, 'JEFF','CENTRO','99','111','10/02/2007');

--C
INSERT INTO TB_CLIENTE VALUES(4, 'MORGAN','CENTRO','99','99','111','23/03/2007');
INSERT INTO TB_CLIENTE VALUES(5, 'MORGAN','CENTRO','99','99','111','23/03/2007');
INSERT INTO TB_CLIENTE VALUES(6, 'MORGAN','CENTRO','99','99','111','23/03/2007');
INSERT INTO TB_CLIENTE VALUES(7, 'MORGAN','CENTRO','99','99','111','23/03/2007');

--6
--A
SELECT CD_CLIENTE,NM_CLIENTE,RG,TELEFONE2 FROM TB_CLIENTE;

--B
SELECT NM_CLIENTE FROM TB_CLIENTE WHERE DT_REGISTRO < '01/03/2007';

--C
SELECT NM_CLIENTE FROM TB_CLIENTE WHERE TELEFONE2 IS NULL;

--7
--A
UPDATE TB_CLIENTE SET TELEFONE2 = '000' WHERE CD_CLIENTE = 5;
--B
UPDATE TB_CLIENTE SET TELEFONE1 = '000', TELEFONE2 = '001' WHERE CD_CLIENTE = 3;

--8
--A 
DELETE FROM TB_CLIENTE WHERE CD_CLIENTE = 4;
DELETE  TB_CLIENTE WHERE CD_CLIENTE = 5;






















