/*[]-----------------------------------------------------------------[]*/
/*|                     CERTIFICAÇÃO OCA                              |*/
/*|*******************************************************************|*/
/*|  BOOK.......: OCA ORACLE DATABASE       DATA..: 22.10.2018	      |*/
/*|  CAP_02.....: ORACLE	AND	STRUCTURED	QUERY	LANGUAGE (SQL)    |*/
/*|  @AUTHOR....: JEFFERSON                                           |*/
/*|  INFO.......: LABORATÓRIO 01 – COMANDOS DDL                       |*/
/*[]-----------------------------------------------------------------[]*/

--1 
CREATE SEQUENCE SQ_ID
START WITH 1
INCREMENT BY 1;

--A
CREATE TABLE TB_DVD(
    CD_DVD NUMBER CONSTRAINT PK_CD_DVD PRIMARY KEY,
    TITULO VARCHAR2(20),
    CATEGORIA VARCHAR2(20)
);

CREATE TABLE TB_CLIENTE(
    CD_CLIENTE NUMBER,
    NOME_CLIENTE VARCHAR2(20)
);
--B
ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_CD_CLIENTE PRIMARY KEY(CD_CLIENTE);


CREATE TABLE TB_LOCACAO(
    CD_CLIENTE NUMBER,
    CD_DVD NUMBER,
    VALOR NUMBER(10,2),
    DT_LOCACAO DATE,
    DT_DEVOLUCAO DATE
);

--C
ALTER TABLE TB_LOCACAO ADD CONSTRAINT PK_LOCACAO PRIMARY KEY
(CD_CLIENTE,CD_DVD,DT_LOCACAO);

--D
ALTER TABLE TB_LOCACAO ADD CONSTRAINT FK_TB_DVD FOREIGN KEY
(CD_DVD)REFERENCES TB_DVD(CD_DVD);

--E
ALTER TABLE TB_LOCACAO
    ADD CONSTRAINT FK_TB_CLIENTE FOREIGN KEY ( CD_CLIENTE )
        REFERENCES TB_CLIENTE ( CD_CLIENTE );


ALTER TABLE TB_DVD DROP CONSTRAINT FK_TB_DVD;

--2
ALTER TABLE TB_DVD ADD ANO_LANCAMENTO DATE;

--3
ALTER TABLE TB_CLIENTE ADD(
    ENDERECO VARCHAR2(20),
    CPF VARCHAR2(20)
);
